stages:
  data_ingestion:
    cmd: python src/CnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image